#!/bin/bash

# Generated by Copilot
# Test script for Food APIs: Create, Search, and Get by ID
# This script tests the food-related endpoints of the nutrient API

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
BASE_URL="${BASE_URL:-http://localhost:8080}"
API_BASE="${BASE_URL}/api/v1"

# Test user credentials (you should register first or use existing credentials)
TEST_EMAIL="${TEST_EMAIL:-test@example.com}"
TEST_PASSWORD="${TEST_PASSWORD:-testpass123}"

echo -e "${YELLOW}=== Food API Test Script ===${NC}\n"

# Step 1: Login to get JWT token
echo -e "${YELLOW}Step 1: Authenticating...${NC}"
LOGIN_RESPONSE=$(curl -s -X POST "${API_BASE}/auth/login" \
  -H "Content-Type: application/json" \
  -d "{
    \"email\": \"${TEST_EMAIL}\",
    \"password\": \"${TEST_PASSWORD}\"
  }")

# Extract token from response (assuming response format has accessToken field)
TOKEN=$(echo $LOGIN_RESPONSE | grep -o '"accessToken":"[^"]*' | cut -d'"' -f4)

if [ -z "$TOKEN" ]; then
  echo -e "${RED}❌ Login failed. Please check credentials or register first.${NC}"
  echo "Response: $LOGIN_RESPONSE"
  echo ""
  echo "To register a new user, run:"
  echo "curl -X POST ${API_BASE}/auth/register \\"
  echo "  -H 'Content-Type: application/json' \\"
  echo "  -d '{\"email\":\"${TEST_EMAIL}\",\"password\":\"${TEST_PASSWORD}\",\"profile\":{\"name\":\"Test User\"}}'"
  exit 1
fi

echo -e "${GREEN}✓ Authentication successful${NC}\n"

# Step 2: Create a food item
echo -e "${YELLOW}Step 2: Creating a food item...${NC}"
CREATE_RESPONSE=$(curl -s -X POST "${API_BASE}/foods" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${TOKEN}" \
  -d '{
    "name": {
      "en": "Grilled Chicken Breast",
      "vi": "Ức gà nướng"
    },
    "searchTerms": ["chicken", "breast", "grilled", "protein"],
    "description": {
      "en": "Lean protein source, perfect for muscle building",
      "vi": "Nguồn protein nạc, hoàn hảo cho việc xây dựng cơ bắp"
    },
    "category": "protein",
    "macros": {
      "protein": 31.0,
      "carbohydrates": 0.0,
      "fat": 3.6,
      "fiber": 0.0,
      "sugar": 0.0
    },
    "micros": {
      "vitaminA": 20.0,
      "vitaminC": 0.0,
      "calcium": 15.0,
      "iron": 0.7,
      "sodium": 84.0,
      "potassium": 256.0
    },
    "servingSizes": [
      {
        "unit": "gram",
        "amount": 100,
        "description": "100 grams",
        "gramEquivalent": 100
      },
      {
        "unit": "piece",
        "amount": 1,
        "description": "1 piece (about 200g)",
        "gramEquivalent": 200
      }
    ],
    "calories": 165.0,
    "visibility": "public",
    "imageUrl": "https://example.com/chicken-breast.jpg"
  }')

echo "$CREATE_RESPONSE" | jq '.' 2>/dev/null || echo "$CREATE_RESPONSE"
echo ""

# Check if creation was successful
if echo "$CREATE_RESPONSE" | grep -q "created successfully"; then
  echo -e "${GREEN}✓ Food created successfully${NC}\n"
else
  echo -e "${RED}❌ Food creation failed${NC}\n"
fi

# Step 3: Search for food items
echo -e "${YELLOW}Step 3: Searching for food items...${NC}"
SEARCH_RESPONSE=$(curl -s -X GET "${API_BASE}/foods/search?query=chicken&limit=10&offset=0" \
  -H "Authorization: Bearer ${TOKEN}")

echo "$SEARCH_RESPONSE" | jq '.' 2>/dev/null || echo "$SEARCH_RESPONSE"
echo ""

# Extract first food ID from search results for testing Get by ID
FOOD_ID=$(echo "$SEARCH_RESPONSE" | grep -o '"id":"[^"]*' | head -1 | cut -d'"' -f4)

if [ -n "$FOOD_ID" ]; then
  echo -e "${GREEN}✓ Found food ID: ${FOOD_ID}${NC}\n"
  
  # Step 4: Get food by ID
  echo -e "${YELLOW}Step 4: Getting food by ID...${NC}"
  GET_RESPONSE=$(curl -s -X GET "${API_BASE}/foods/${FOOD_ID}" \
    -H "Authorization: Bearer ${TOKEN}")
  
  echo "$GET_RESPONSE" | jq '.' 2>/dev/null || echo "$GET_RESPONSE"
  echo ""
  
  if echo "$GET_RESPONSE" | grep -q "\"id\""; then
    echo -e "${GREEN}✓ Successfully retrieved food by ID${NC}\n"
  else
    echo -e "${RED}❌ Failed to retrieve food by ID${NC}\n"
  fi
else
  echo -e "${YELLOW}⚠ No food ID found in search results, skipping Get by ID test${NC}\n"
fi

# Step 5: Test search with different query
echo -e "${YELLOW}Step 5: Testing search with different query (protein)...${NC}"
SEARCH_PROTEIN=$(curl -s -X GET "${API_BASE}/foods/search?query=protein&limit=5&offset=0" \
  -H "Authorization: Bearer ${TOKEN}")

echo "$SEARCH_PROTEIN" | jq '.' 2>/dev/null || echo "$SEARCH_PROTEIN"
echo ""

echo -e "${GREEN}=== Test completed ===${NC}"

