server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"
  read_timeout: 10
  write_timeout: 10
  shutdown_timeout: 30

database:
  uri: "mongodb://localhost:27017"
  database: "nutrient_db"
  max_pool_size: 100
  min_pool_size: 10
  connect_timeout: 10

auth:
  jwt_secret: "${JWT_SECRET}"
  jwt_expiration: 3600
  refresh_expiration: 604800

nats:
  url: "nats://localhost:4222"
  enabled: false

logger:
  level: "debug"
  development: true
  encoding: "console"
